parameters:
- name: platform
  type: string
- name: python_env
  type: string
  default: default
  values:
  - default
  - noop
  - venv

steps:

# UsePythonVersion task only works when the specific Python version is already installed.

# The following is for linux.
# Reference: https://dev.to/akaszynski/create-an-azure-self-hosted-agent-without-going-insane-173g
# Self-hosted agents must provision the modern Python baseline.
# --system-site-packages is required to make packages installed with --user visible to virtualenv.
- script: |
    set -e
    mkdir -p $(Agent.ToolsDirectory)/Python
    cd $(Agent.ToolsDirectory)/Python
    PYTHON_VER=$(python3.10 -c "import sys; print('.'.join([f'{val}' for val in sys.version_info[:3]]))")
    mkdir -p $PYTHON_VER
    ln -sfn $PYTHON_VER 3.10
    cd $PYTHON_VER
    python3.10 -m venv x64 --system-site-packages
    touch x64.complete
  displayName: Create Python 3.10 venv
  condition: and(succeeded(), eq('${{ parameters.python_env }}', 'venv'))

- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.10'
  displayName: Configure Python version
  condition: and(succeeded(), ne('${{ parameters.python_env }}', 'noop'))

- task: NodeTool@0
  inputs:
    versionSpec: 18.15.0
  displayName: Configure Node.js version

- script: |
    python -m pip install -r dependencies/setup.txt
  displayName: Install PyPA tools
